steps:
- args:
  - build
  - -t
  - gcr.io/ownproy/github.com/paolobe/resthelper:$COMMIT_SHA
  - -f
  - Dockerfile
  - .
  name: gcr.io/cloud-builders/docker
images:
- gcr.io/ownproy/github.com/paolobe/resthelper:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY